version: "3"

services:
  app:
    build: .
    ports:
      - "3000:3000"
    command: npm run dev
    restart: always
    volumes:
      - .:/usr/app
    environment:
      - REACT_APP_BACK=localhost:3000
